/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_6200.testdb322.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_6200.testdb322.*;


/**
 * ServiceImpl object for domain model class Table2.
 * @see com.test_6200.testdb322.Table2
 */
@Service("testdb322.Table2Service")
public class Table2ServiceImpl implements Table2Service {


    private static final Logger LOGGER = LoggerFactory.getLogger(Table2ServiceImpl.class);

    @Autowired
    @Qualifier("testdb322.Table2Dao")
    private WMGenericDao<Table2, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Table2, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "testdb322TransactionManager")
     public Page<Table2> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }


    @Transactional(readOnly = true, value = "testdb322TransactionManager")
    @Override
    public Page<Table2> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all table2s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "testdb322TransactionManager")
    @Override
    public Page<Table2> findAll(Pageable pageable) {
        LOGGER.debug("Finding all table2s");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "testdb322TransactionManager")
    @Override
    public Table2 findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding table2 by id: {}" , id);
        Table2 table2=this.wmGenericDao.findById(id);
        if(table2==null){
            LOGGER.debug("No table2 found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return table2;
    }

    @Transactional(readOnly = true, value = "testdb322TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


